[tools]
rojo = "rojo-rbx/rojo@7.4.4"
wally = "upliftgames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.4.2"
luau-lsp = "JohnnyMorganz/luau-lsp@1.38.1"
selene = "kampfkarren/selene@0.28.0"
stylua = "JohnnyMorganz/StyLua@2.0.2"
